apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    app: pod-nginx
spec:
  containers:
    - name: container-nginx-1
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /volume-container
          name: teste-volume

    - name: container-jenkins-2
      image: jenkins/jenkins:alpine3.22-jdk21
      ports:  
        - containerPort: 8080
      volumeMounts: 
        - mountPath: /volume-container
          name: teste-volume
  volumes:
    - name: teste-volume
      hostPath:
        path: /home/docker/volume
        type: Directory #DirectoryOrCreate