apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  selector:
    app: pod-1 
  ports: 
  - port: 9000  # porta onde o serviço recebe as requisições
    targetPort: 80 #porta para onde o serviço encaminha as requisições
    nodePort: 32300 #porta onde o serviço é acessado externamente. O acesso é pelo ip de um dos nós do cluster. Serviço exposto em todos os nós do cluster
