apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-db-noticias
spec:
  template:
    metadata:
      name: db-noticias
      labels:
        app: bd-noticias
    spec:
      containers:
      - name: container-db-noticias
        image: aluracursos/mysql-db:1
        ports:
          - containerPort: 3306
        envFrom:
          - configMapRef:
              name: db-noticias-cm
  replicas: 1
  selector:
    matchLabels:
      app: bd-noticias
