apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    app: bd-noticias
spec:
  containers:
  - name: container-db-noticias
    image: aluracursos/mysql-db:1
    ports:
      - containerPort: 3306
    envFrom:
      - configMapRef:
          name: db-noticias-cm
