apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-portal-noticias
spec:
  template:
    metadata:
      name: app-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias
          image: aluracursos/portal-noticias:1
          envFrom:
            - configMapRef:
                name: portal-noticias-cm
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias

