apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-sistema-noticias
spec:
  template:
    metadata:
      name: container-sistema-noticias
      labels:
        app: sistema-noticias
    spec:
      containers:
      - name: container-sistema-noticias
        image: aluracursos/sistema-noticias:1
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: sistema-noticias-cm
  replicas: 1
  selector:
    matchLabels:
      app: sistema-noticias