apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-imagens-sistema-noticias
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard