apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sistema-noticias-statefulset
spec:
  selector:
    matchLabels:
      app: sistema-noticias
  serviceName: svc-sistema-noticias
  replicas: 2
  template:
    metadata:
      name: sistema-noticias
      labels:
        app: sistema-noticias
    spec:
      containers:
      - name: container-sistema-noticias
        image: aluracursos/sistema-noticias:1
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: sistema-noticias-cm
        volumeMounts:
          - name: imagens
            mountPath: /var/www/html/uploads
          - name: sessao
            mountPath: /tmp
      volumes:
        - name: imagens
          persistentVolumeClaim:
            claimName: pvc-imagens-sistema-noticias
        - name: sessao
          persistentVolumeClaim:
            claimName: pvc-sessao-sistema-noticias

          
